### ISSUE TITLE
获取zone_id失败

### ISSUE THREAD

**Issue by londbell** [nICEnnnnnnnLee/GithubSoEasy#10]
Traceback (most recent call last):
  File "/Users/xxx/Downloads/GithubSoEasy-master/create_workers.py", line 214, in <module>
    method()
  File "/Users/xxx/Downloads/GithubSoEasy-master/create_workers.py", line 199, in method
    zone_id = cf_worker.get_zone_id(domain=HOME_DOMAIN)
  File "/Users/xxx/Downloads/GithubSoEasy-master/create_workers.py", line 40, in get_zone_id
    return res["result"][0]["id"]
IndexError: list index out of range

**Comment by Ausli** [comment]
需要cf挂域名
